export default {
  INITIALIZE_DISCUSSIONS_LIST: "INITIALIZE_DISCUSSIONS_LIST",
  UPDATE_DISCUSSIONS_LIST: "UPDATE_DISCUSSIONS_LIST",
  UPDATE_COMMENT: "UPDATE_COMMENT",
  STORE_AUTH_INFO: "STORE_AUTH_INFO",
};
