export default {
  INITIALIZE_BOARD: "INITIALIZE_BOARD",
  MOVE_PIECE: "MOVE_PIECE",
  STORE_CURRENT_POSITION: "STORE_CURRENT_POSITION",
  STORE_VALID_POSITIONS: "STORE_VALID_POSITIONS",
  CLEAR_VALID_POSITIONS: "CLEAR_VALID_POSITIONS",
  GET_KING_POSITION: "GET_KING_POSITION",
  KING_IN_CHECK: "KING_IN_CHECK",
};
